### PR TITLE
Remove hyperzsh reference

### PR DESCRIPTION
**Pull request by chabou**
[hyperzsh](https://www.npmjs.com/package/hyperzsh) have nothing to do with hyper 😆

### CODE REVIEW

**Comment by iamstarkov** [comment]
@chabou what do you mean?

**Comment by chabou** [comment]
Hyperzsh is an hyperminimalist zsh theme. No link with our hyper app. Or maybe I didn't get it...

**Comment by freddinator** [comment]
It does say
> Hyperzsh was built with Hyper.app in mind. The demo above uses my custom color scheme called hyperblue. You can automatically configure hyperblue by adding 'hyperblue' to the plugins section in ~/.hyperterm.js.

in the README, so it's at least vaguely related.

**Comment by chabou** [comment]
oh, you're right... vaguely related. I haven't see it.
But "Zsh for Hyper." description is wrong.

If you have hyper in mind or designing a theme for it, I think you don't put git information in prompt anymore because there is now some plugins to do this (https://www.npmjs.com/package/hyper-statusline). Even more if you want a minimalist theme in zsh.

But ok, hyperzsh is related

**Pull request closed without merging**
