### PR TITLE
Added Theme: hypermaterial-vibrancy

### PR DESCRIPTION
**Pull request by danielheyman**
Added "hypermaterial-vibrancy" to the theme list - https://github.com/danielheyman/hypermaterial-vibrancy

## Checklist for submitting an `awesome` plugin, theme, or resource:

- [x] The title for my package or theme uses its npm title (`hyper-plugin-example`)
- [x] The link for my package or theme uses the npmjs.com link (https://www.npmjs.com/package/hyper-plugin-example)
- [x] There is a visual representation of what my plugin or theme does in the repo. (Plugin: screenshot or gif || Theme: screenshot of the theme applied to Hyper)
- [x] Put your awesome item at the **BOTTOM** of the correct (plugin, theme, or resource) list.
- [x] **VERY IMPORTANT:** I've written a short (one sentence) description for my package or theme as the description of the awesome plugin, theme, or resource in the README.md file I'm submitting in the PR.

### CODE REVIEW

**Comment by iamstarkov** [comment]
thats bad https://github.com/dotcypress/hyper-material-vibrancy/compare/master...danielheyman:master

**Comment by iamstarkov** [comment]
you dont own rights to that theme

**Comment by danielheyman** [comment]
Hi, the license says "including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software". I gave him copyright credit in the license as requested. The theme stopped working as I explained in one of the posts: "Hi, I have been quite interested in the material vibrancy theme that was on here in the past but it had a lot of issues with compatibility and vibrancy wasn't working. I've updated it and published it here if you're interested in adding it to the list: https://www.npmjs.com/package/hypermaterial-vibrancy" as posted here: https://github.com/bnb/awesome-hyper/issues/211

**Comment by iamstarkov** [comment]
There is no copyright credit in [license](https://github.com/dotcypress/hyper-material-vibrancy/compare/master...danielheyman:master#diff-9879d6db96fd29134fc802214163b95a). I wouldnt you submit pull-request to original repo?

**Comment by danielheyman** [comment]
@iamstarkov The copyright is in the license file on the first line "Copyright (c) 2016 Vitaly Domnikov". I am not doing a pull-request because I'm making many changes to the theme and just using his content as the base. I'm planning on adding configurations and other customizations based on my preferences that may not match his.

**Comment by danielheyman** [comment]
@iamstarkov I'm not against pull-requests. I've created pull-requests to other packages on the list. I just figured that it is in the best interest of both of us to keep it separate since I'm going to customize it in ways that may not match with Vitaly's interests.

**Comment by iamstarkov** [comment]
i dont get it. there is not traits of you in original repo's issues or pull-requests. In fact, no one opened any issues. and regarding pull-requests, @dotcypress is quite nice about 'em

**Pull request closed without merging**
