### PR TITLE
added hyper-zigorat theme

### PR DESCRIPTION
**Pull request by dotamir**
## Checklist for submitting an `awesome` plugin, theme, or resource:

- [x] The title for my package or theme uses its npm title (`hyper-plugin-example`)
- [x] The link for my package or theme uses the npmjs.com link (https://www.npmjs.com/package/hyper-plugin-example)
- [x] There is a visual representation of what my plugin or theme does in the repo. (Plugin: screenshot or gif || Theme: screenshot of the theme applied to Hyper)
- [x] Put your awesome item at the **BOTTOM** of the correct (plugin, theme, or resource) list.
- [x] **VERY IMPORTANT:** I've written a short (one sentence) description for my package or theme as the description of the awesome plugin, theme, or resource in the README.md file I'm submitting in the PR.

### CODE REVIEW

**Comment by matheuss** [comment]
@dotamir would you mind adding a screenshot of the theme to its `README.md`? 😅

**Comment by dotamir** [comment]
Oh sorry :smile: 
now added screenshot to README.md .

**Comment by bnb** [comment]
@dotamir Looks like the screenshot's broken 😟 If you could fix it, I'd be happy to fix the README.md and merge this!

**Comment by dotamir** [comment]
@bnb I checked this problem, It's Ok.

**Comment by iamstarkov** [comment]
> I checked this problem, It's Ok.

@dotamir, what do you mean?

**Comment by iamstarkov** [comment]
@dotamir seems like screenshot isnt fixed
screen shot 2016-12-10 at 2 57 06 am

**Comment by iamstarkov** [comment]
image pointed to `Screenshot.png`

**Comment by iamstarkov** [comment]
oh, i see

**Comment by iamstarkov** [comment]
there are two options, why this is happening:

1) you added a screenshot, but didnt publish new version
2) npm rendering is broken somehow, if its the case, then just replicate how other themes includes images, likey hyperterm-ayu https://raw.githubusercontent.com/licatajustin/hyperterm-ayu/master/README.md

**Comment by iamstarkov** [comment]
and can you rename a project to hyper-zigorat?

**Comment by dotamir** [comment]
@iamstarkov @bnb sorry for problems :)
renamed to 'hyper-zigorat' and screenshot fixed. everything it's ok.

**Comment by iamstarkov** [comment]
your changes are now fine

**Comment by iamstarkov** [comment]
but master branch has been updated several time now, can you rebase your branch on latest master?

**Pull request merged**
