### PR TITLE
adding Ganymede

### PR DESCRIPTION
**Pull request by charlespeters**
## Checklist for submitting an `awesome` plugin, theme, or resource:
- [x] The title for my package or theme uses its npm title (`hyper-plugin-example`)
- [x] The link for my package or theme uses the npmjs.com link (https://www.npmjs.com/package/hyper-plugin-example)
- [x] There is a visual representation of what my plugin or theme does in the repo. (Plugin: screenshot or gif || Theme: screenshot of the theme applied to Hyper)
- [x] Put your awesome item at the **BOTTOM** of the correct (plugin, theme, or resource) list.
- [x] **VERY IMPORTANT:** I've written a short (one sentence) description for my package or theme as the description of the awesome plugin, theme, or resource in the README.md file I'm submitting in the PR.

### CODE REVIEW

**Comment by chadxz** [comment]
no screenshot

**Comment by charlespeters** [comment]
@chadxz there's one in the repo https://github.com/charlespeters/hyperganymede how do you make those links work on NPM?

**Comment by chadxz** [comment]
in your package.json, use the "[repository](https://docs.npmjs.com/files/package.json#repository)" config section

**Comment by chadxz** [comment]
You'll probably need to publish what's currently on your master branch to npm to get the README to update there. Not sure how it will handle the relative links to the images, but publishing what's there should at least let you see if it will work as-is or not.

**Comment by charlespeters** [comment]
should be resolved now https://www.npmjs.com/package/hyperganymede

**Comment by bnb** [comment]
Fantastic! Merging now. Thanks a ton @chadxz for reviewing! ❤️

**Comment by chadxz** [comment]
np

**Pull request merged**
