### PR TITLE
Added hyperterm-vmc-dark

### PR DESCRIPTION
**Pull request by vemec**
## Checklist for submitting an `awesome` plugin, theme, or resource:

- [X] The title for my package or theme uses its npm title (`hyper-plugin-example`)
- [X] The link for my package or theme uses the npmjs.com link (https://www.npmjs.com/package/hyper-plugin-example)
- [X] There is a visual representation of what my plugin or theme does in the repo. (Plugin: screenshot or gif || Theme: screenshot of the theme applied to Hyper)
- [X] Put your awesome item at the **BOTTOM** of the correct (plugin, theme, or resource) list.
- [X] **VERY IMPORTANT:** I've written a short (one sentence) description for my package or theme as the description of the awesome plugin, theme, or resource in the README.md file I'm submitting in the PR.

### CODE REVIEW

**Comment by matheuss** [comment]
@vemec could you change it from `hyperterm` to `hyper`? 😅 You can rename the package on npm 😄

**Comment by simonmeusel** [comment]
@vemec Because of https://zeit.co/blog/the-hyper-plan

**Comment by bnb** [comment]
@simonmeusel Yes, that is the reason why changing from _hyperterm_ to _hyper_ would be ideal. 😊

**Comment by iamstarkov** [comment]
@vemec ping

**Comment by bnb** [comment]
Closing this - outstanding request for updated information since October. Happy to re-open if there's an update, @vemec. ❤️

**Pull request closed without merging**
