### PR TITLE
Add `hyper-terminal-tabs` customization

### PR DESCRIPTION
**Pull request by rafaelrinaldi**
Brings Terminal.app look and feel to Hyper.

## Checklist for submitting an `awesome` plugin, theme, or resource:

- [x] The title for my package or theme uses its npm title (`hyper-plugin-example`)
- [x] The link for my package or theme uses the npmjs.com link (https://www.npmjs.com/package/hyper-plugin-example)
- [x] There is a visual representation of what my plugin or theme does in the repo. (Plugin: screenshot or gif || Theme: screenshot of the theme applied to Hyper)
- [x] Put your awesome item at the **BOTTOM** of the correct (plugin, theme, or resource) list.
- [x] **VERY IMPORTANT:** I've written a short (one sentence) description for my package or theme as the description of the awesome plugin, theme, or resource in the README.md file I'm submitting in the PR.

### CODE REVIEW

**Comment by iamstarkov** [comment]
yo, image is broken in the README https://www.npmjs.com/package/hyper-terminal-tabs

**Comment by iamstarkov** [comment]
@rafaelrinaldi can i ask you to fix that?

**Comment by rafaelrinaldi** [comment]
@iamstarkov That's very weird. If you look at the GitHub page it works perfectly but on the npm website it looks broken. Looks like a bug on npm's side?

**Comment by iamstarkov** [comment]
nah, link to image is local, github is aware of pictures in your repo and can render them, npm is not aware and shouldnt be.

**Comment by iamstarkov** [comment]
so, just point to absolute url

**Comment by rafaelrinaldi** [comment]
@iamstarkov yeah, I just thought that npm did that automatically for some reason. Will change and send you as soon as I can (AFK right now).

**Comment by bnb** [comment]
It's a super annoying difference between GitHub and npm's public display. We run into it constantly 😅

**Comment by rafaelrinaldi** [comment]
@iamstarkov @bnb Should be good to go now 👍

**Comment by iamstarkov** [comment]
@rafaelrinaldi merged, thanks!

**Pull request merged**
