### PR TITLE
Added hyper-cat to Fun section

### PR DESCRIPTION
**Pull request by Aaronius**
From the repository at https://github.com/Aaronius/hyper-cat.

## Checklist for submitting an `awesome` plugin, theme, or resource:

- [X] The title for my package or theme uses its npm title (`hyper-plugin-example`)
- [X] The link for my package or theme uses the npmjs.com link (https://www.npmjs.com/package/hyper-plugin-example)
- [X] There is a visual representation of what my plugin or theme does in the repo. (Plugin: screenshot or gif || Theme: screenshot of the theme applied to Hyper)
- [X] Put your awesome item at the **BOTTOM** of the correct (plugin, theme, or resource) list.
- [X] **VERY IMPORTANT:** I've written a short (one sentence) description for my package or theme as the description of the awesome plugin, theme, or resource in the README.md file I'm submitting in the PR.

### CODE REVIEW

**Comment by Aaronius** [comment]
You're right! I forgot there was a fun category. I'll move it there and add a license file to my repo. Thanks for the tips.

**Comment by Aaronius** [comment]
Okay, updated!

**Comment by iamstarkov** [comment]
@Aaronius love your plugin

**Comment by Aaronius** [comment]
Thanks! Pretty impractical but a lot of fun.

**Comment by katopz** [comment]
@Aaronius I think I love you and your plugin! 😍

**Comment by zeke** [comment]
200w

**Pull request merged**
