### PR TITLE
hyperterm-1password no longer works

### PR DESCRIPTION
**Pull request by jspiro**
1Password removed the functionality a while back.

## Checklist for submitting a resource to `awesome-hyper`:

- [ ] **Title:** The title for the addition uses its npm title (`hyper-example`) or the resource's title.
- [ ] **Link:** The link for the addition uses the npmjs.com link (`https://www.npmjs.com/package/hyper-example`) or the resource's full URI.
- [ ] **Repository:** The `package.json` file of the resource contains [repository information](https://docs.npmjs.com/files/package.json#repository).
- [ ] **Visual:** There is a visual representation of what the addition does in its source repository.
- [ ] **Location:** The awesome addition is in the correct category or sub-category.
  - If it's a **plugin or resource**, put your awesome item at the **BOTTOM** of the correct section.
  - If it's a **theme**, insert it according to the **ALPHABETICAL** order.
- [ ] **Description:** I've written a short (one sentence) description for the addition in the `README.md`.
- [ ] **Downloads:** I've added a download stats badge in the second column (`[npm]()`)

### CODE REVIEW

**Comment by darahak** [comment]
Related issue in case people want to know more: https://github.com/sibartlett/hyperterm-1password/issues/9

**Comment by jspiro** [comment]
Yeah, it was unclear to me how to do that given there is no pattern for this deprecation in the readme.

It wastes a ton of time for someone new to hyper coming and trying this and wondering why it doesn't work. It also seems like the plugin development has stopped anyway.

Maybe a section for deprecated or dying plugins?

**Comment by hugomano** [comment]
I'm working on [1password-node](https://github.com/hugomano/1password-node). A wrapper around the CLI client. Feel free to give a try ! Mac & Windows for now but Linux is coming..

**Comment by wadewegner** [comment]
You should move `hyperterm-1password` from the main list as it no longer works.

See: https://twitter.com/1Password/status/1046424465637289984

**Pull request merged**
