### PR TITLE
Add hyper-match to productivity

### PR DESCRIPTION
**Pull request by delcore92**
## Checklist for submitting a resource to `awesome-hyper`:

- [x] **Title:** The title for the addition uses its npm title (`hyper-example`) or the resource's title.
- [x] **Link:** The link for the addition uses the npmjs.com link (`https://www.npmjs.com/package/hyper-example`) or the resource's full URI.
- [x] **Repository:** The `package.json` file of the resource contains [repository information](https://docs.npmjs.com/files/package.json#repository).
- [x] **Visual:** There is a visual representation of what the addition does in its source repository.
- [x] **Location:** The awesome addition is in the correct category or sub-category.
  - If it's a **plugin or resource**, put your awesome item at the **BOTTOM** of the correct section.
  - If it's a **theme**, insert it according to the **ALPHABETICAL** order.
- [x] **Description:** I've written a short (one sentence) description for the addition in the `README.md`.
- [x] **Downloads:** I've added a download stats badge in the second column (`[npm]()`)

## Plugin Info
demo

Hyper-match lets you bind triggers to patterns such as urls and emails.

### CODE REVIEW

**Comment by chabou** [comment]
Be careful: I think that your plugin won't work with Hyper V2 (available on canary update channel).
It uses a lot of deprecated functions. 

(btw it makes me sad because it a wonderful plugin with a lot of work 😞 )

**Comment by delcore92** [comment]
Oh! Thanks for the heads up @chabou. That's my fault, i should have checked was in the works for Hyper before i started :man_facepalming:. I'll switch over to canary to see what needs to be done to support V2. 

Glad you like the plugin ;)

**Comment by delcore92** [comment]
Will v2 support be a blocker for this pr?

**Comment by bnb** [comment]
LGTM 🚢

**Pull request merged**
