### PR TITLE
Add hyperterm-themed-scrollbar to packages list

### PR DESCRIPTION
**Pull request by cdransf**
Checklist for submitting an awesome plugin, theme, or resource:

- [x] The title for my package or theme uses its npm title (hyper-plugin-example)
 The link for my package or theme uses the npmjs.com link (https://www.npmjs.com/package/hyper-plugin-example)
- [x] There is a visual representation of what my plugin or theme does in the repo. (Plugin: screenshot or gif || Theme: screenshot of the theme applied to Hyper)
- [x] Put your awesome item at the BOTTOM of the correct (plugin, theme, or resource) list.
- [x] VERY IMPORTANT: I've written a short (one sentence) description for my package or theme as the description of the awesome plugin, theme, or resource in the README.md file I'm submitting in the PR.

### CODE REVIEW

**Comment by iamstarkov** [comment]
@cdransf why did you do close an issue?

**Comment by cdransf** [comment]
@iamstarkov I believe I misunderstood the requirements for contributing to the repo so I closed the issue. Sorry!

**Comment by iamstarkov** [comment]
nah, everything is good. its hyperterm which was renamed to hyper, so we are asking people to rename themes/plugins as well. no worries

**Comment by iamstarkov** [comment]
> The repository that submitted this pull request has been deleted.

=(

**Comment by cdransf** [comment]
Ah,  understood. I hadn't authored it but thought it warranted being included.

**Pull request closed without merging**
