### PR TITLE
added hyperterm-clicky

### PR DESCRIPTION
**Pull request by capaj**
## Checklist for submitting an `awesome` plugin, theme, or resource:

- [x] The title for my package or theme uses its npm title (`hyperterm-plugin-example`)
- [x] The link for my package or theme uses the npmjs.com link (https://www.npmjs.com/package/hyperterm-plugin-example)
- [x] There is a visual representation of what my plugin or theme does in the repo. (Plugin: screenshot or gif || Theme: screenshot of the theme applied to HyperTerm)
- [x] Put your awesome item at the **BOTTOM** of the correct (plugin, theme, or resource) list.
- [x] **VERY IMPORTANT:** I've written a short (one sentence) description for my package or theme as the description of the awesome plugin, theme, or resource in the README.md file I'm submitting in the PR.

### CODE REVIEW

**Comment by matheuss** [comment]
Thanks for the submission @capaj 😄 Could you:
1) Move it to the bottom of the list?
2) Change the description to remove the reference to the other package? So people don't need to know the other 😌 

Thanks!

**Comment by capaj** [comment]
@matheuss I did not move it to the end because it is similar to hyperlink package. But alright, whatever rocks your boat.

**Comment by capaj** [comment]
@bnb no currently, just URLs and stack traces but the plan is to keep adding new clickable things as requested by the plugin users

**Comment by bnb** [comment]
We can merge. I will as soon as I have a bit - heads-down time right now. :)

**Pull request merged**
