### PR TITLE
List themes in alphabetical order

### PR DESCRIPTION
**Pull request by gsklee**
I left other sections untouched since there might be some recommendation order, but I am pretty sure that the themes section would be better if everything is listed in alphabetical order.

### CODE REVIEW

**Comment by iamstarkov** [comment]
this seems to be good thing to do. though pull-request template have to be updated accordingly then

**Comment by gsklee** [comment]
@iamstarkov Not sure how you'd like to see the template been modified, I think all 5 items are not applicable to this PR.

**Comment by iamstarkov** [comment]
nay, i meant pull-request template for future pull-requests to request include new themes with respect to alphabetical order

**Comment by gsklee** [comment]
@iamstarkov I see where I misunderstood. I've submitted the PR template retouch as a separate PR (#214) since I've rephrased several other parts.

**Comment by iamstarkov** [comment]
@gsklee landed in master! thank you

**Pull request merged**
