### PR TITLE
Add new `hyper-mac-controls` to customization section

### PR DESCRIPTION
**Pull request by krve**
Make the hyperterm close, minimize and maximize buttons look like a mac.

Link to repo: [hyper-mac-controls](https://github.com/krve/hyper-mac-controls)

## Checklist for submitting an `awesome` plugin, theme, or resource:

- [x] The title for my package or theme uses its npm title (`hyper-plugin-example`)
- [x] The link for my package or theme uses the npmjs.com link (https://www.npmjs.com/package/hyper-plugin-example)
- [x] There is a visual representation of what my plugin or theme does in the repo. (Plugin: screenshot or gif || Theme: screenshot of the theme applied to Hyper)
- [x] Put your awesome item at the **BOTTOM** of the correct (plugin, theme, or resource) list.
- [x] **VERY IMPORTANT:** I've written a short (one sentence) description for my package or theme as the description of the awesome plugin, theme, or resource in the README.md file I'm submitting in the PR.

### CODE REVIEW

**Comment by darahak** [comment]
Hello @krve, thanks a lot for the PR.
I just need you to make a few updates before I can merge it.

**Comment by krve** [comment]
@darahak I'll make the changes and change the name of the package as well.

**Comment by krve** [comment]
I've updated the package name, as well as the link.

**Comment by iamstarkov** [comment]
@darahak want to take a look?

**Comment by darahak** [comment]
@krve Oh you went ahead and changed your package name.
I was just referencing the "HyperTerm" from the short description text, but that's really good.

Would you mind updating this part? (it's my last request I swear :smile: )

**Comment by krve** [comment]
@darahak haha, I just updated the description :smile:

**Pull request merged**
