### PR TITLE
Feat/add hyper pane

### PR DESCRIPTION
**Pull request by iamstarkov**
navigate through panes with arrows — plugin we all wanted
https://www.npmjs.com/package/hyper-pane

/cc @chabou

### CODE REVIEW

**Comment by darahak** [comment]
Nothing to do with the PR, but we get `429` HTTP errors on the CI tests now ("too many requests").
Is there a way to throttle these requests?

**Comment by chabou** [comment]
@iamstarkov ❤️  you made my day

I would suggest to not mention shortcut because it will be configurable very soon.
Something like: "Navigate through panes with arrows or jump directly to a specific pane with digit" or something like that.
(No need to mention "switch" functionality)

**Comment by iamstarkov** [comment]
@chabou fixed description here and i think you would need to update yours github/npm/readme descriptions as well =)

**Comment by iamstarkov** [comment]
@darahak 
> Is there a way to throttle these requests?

i dont know, why do we need to use API for linting README files

**Comment by darahak** [comment]
It looks for dead links, so I guess it's useful but it generates a lot of false positives :man_shrugging: 
Probably something to be discussed on #180

**Pull request merged**
